server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #服务端的实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false  #表示自端就是注册中心，我的职责就是维护实例，并不需要去检索服务
    service-url:
      ## 设置与Eurefa Service交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #单机就是7001自己
      defaultZone: http://eureka7001.com:7001/eureka/
      ## 集群模式下地址，要与7002相互守望
#      defaultZone: http://eureka7002.com:7002/eureka/

#    server:
#      ##关闭自我保护机制，保证不可用服务被及时踢除 true 开启
#      enable-self-preservation: false
#      eviction-interval-timer-in-ms: 2000